name: stylelezza
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.2.1
  flutter_svg: any
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  pinput: ^5.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  book_my_seat: any
  http: ^1.2.2
  flutter_map: ^7.0.2
  interactiveviewer_gallery: ^0.6.0
  url_launcher: ^6.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  country_picker: ^2.0.27
  intl: ^0.20.1
  google_generative_ai: ^0.4.6
  flutter_inappwebview: ^6.1.5
  dart_levenshtein: ^1.0.1
  fuzzywuzzy: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21
  


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
    - assets/icon/icon.png
    - assets/logo/
