// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLBq4V5MYcC5dRa0MrBZS-rbjt3pu0AOc',
    appId: '1:404129484872:web:8b458b6e8236f5adfb887d',
    messagingSenderId: '404129484872',
    projectId: 'stylelezza045',
    authDomain: 'stylelezza045.firebaseapp.com',
    storageBucket: 'stylelezza045.appspot.com',
    measurementId: 'G-9RHDTB6Z6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGHw3alEBHjutEkS95Ji2V_pKhcQVcnZw',
    appId: '1:404129484872:android:2d64107d15e5d588fb887d',
    messagingSenderId: '404129484872',
    projectId: 'stylelezza045',
    storageBucket: 'stylelezza045.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX728-6wmThz4lSnZ47lEtLXwW5CvrCHI',
    appId: '1:404129484872:ios:739925157bb301a9fb887d',
    messagingSenderId: '404129484872',
    projectId: 'stylelezza045',
    storageBucket: 'stylelezza045.appspot.com',
    iosBundleId: 'com.example.stylelezza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX728-6wmThz4lSnZ47lEtLXwW5CvrCHI',
    appId: '1:404129484872:ios:739925157bb301a9fb887d',
    messagingSenderId: '404129484872',
    projectId: 'stylelezza045',
    storageBucket: 'stylelezza045.appspot.com',
    iosBundleId: 'com.example.stylelezza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLBq4V5MYcC5dRa0MrBZS-rbjt3pu0AOc',
    appId: '1:404129484872:web:40a67f692ecf2408fb887d',
    messagingSenderId: '404129484872',
    projectId: 'stylelezza045',
    authDomain: 'stylelezza045.firebaseapp.com',
    storageBucket: 'stylelezza045.appspot.com',
    measurementId: 'G-XCTHDY65BS',
  );
}
